#ifndef DSRP_ENCPARAMS_HPP
#define DSRP_ENCPARAMS_HPP

#define DSRP_ENCPARAM_LEN_SIZE 2
#define DSRP_ENCPARAM_SEQ_SIZE 8
#define DSRP_ENCPARAM_TRUNCDIGEST_SIZE 12

// DSRP_ENCPARAM_LEN_SIZE + DSRP_ENCPARAM_SEQ_SIZE + DSRP_ENCPARAM_TRUNCDIGEST_SIZE
#define DSRP_ENCPARAM_TOTALOVERHEAD 22

#endif
